services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hooma
    ports:
      - '5432:5432'
    volumes:
      - hooma_pg:/var/lib/postgresql/data
volumes:
  hooma_pg:
