ALTER TABLE "Place" ALTER COLUMN "latitude" DROP NOT NULL;
ALTER TABLE "Place" ALTER COLUMN "longitude" DROP NOT NULL;
ALTER TABLE "FanHub" ALTER COLUMN "latitude" DROP NOT NULL;
ALTER TABLE "FanHub" ALTER COLUMN "longitude" DROP NOT NULL;
