import { Building2, Mail, MapPin, Phone, Plus, Search } from 'lucide-react';

export function PitchPage() {
  return <div className="page-shell vintage-page">
    <section className="border-b vintage-rule pb-5 pt-2"><div className="flex items-end justify-between gap-4"><div><div className="vintage-kicker">Places to play</div><h1 className="vintage-display text-[64px] leading-none">Pitch</h1><p className="mt-1 text-sm muted">Find your pitch. Bring the game.</p></div><button className="vintage-cta px-4" type="button"><Plus size={20}/><span className="hidden sm:inline">Add your place</span></button></div></section>
    <section className="mt-5 grid grid-cols-[1fr_auto] gap-2"><label className="vintage-control flex items-center gap-3 px-4"><Search size={19} style={{color:'var(--hv-lime)'}}/><input className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Search venues, areas..." aria-label="Search pitches"/></label><button className="vintage-control px-4 font-black" type="button">City</button></section>
    <section className="mt-3"><button className="vintage-control px-4 font-black" type="button">Houma</button></section>
    <section className="mt-7"><div className="vintage-torn"><MapPin size={17}/> Nearby venues ★</div><div className="vintage-empty mt-4 p-7 text-center"><span className="vintage-icon mx-auto"><Building2/></span><h2 className="vintage-display mt-4 text-[28px]">No pitches listed yet</h2><p className="mx-auto mt-2 max-w-sm text-sm">Football venue owners can add their place so HOOMA users can find it.</p><button className="vintage-cta mt-5" type="button"><Plus size={19}/> Add your place</button></div></section>
    <section className="mt-8 vintage-panel rounded-[16px] p-5"><div className="vintage-kicker">Venue card contract</div><h2 className="vintage-display mt-1 text-[30px]">Real places. Clear details.</h2><p className="mt-2 text-sm muted">Published Pitch listings will use real venue photography and show City · Houma, hourly rate, and the practical actions below.</p><div className="mt-4 grid grid-cols-3 gap-2 text-xs font-black"><span className="vintage-action flex items-center justify-center gap-1 p-3"><MapPin size={15}/>Address</span><span className="vintage-action flex items-center justify-center gap-1 p-3"><Building2 size={15}/>Houma</span><span className="vintage-action flex items-center justify-center gap-1 p-3"><Phone size={15}/>Contact</span></div><div className="mt-3 hidden"><Mail/></div></section>
  </div>;
}
